// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import { joined } from "../query.js";
import type { Operation, QueryValue, RequestBody } from "../operation.js";
import type { components, paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.DetailedActivity` as the document declares it. */
export type DetailedActivity = components["schemas"]["DetailedActivity"];

/** `components.schemas.StreamSet` as the document declares it. */
export type StreamSet = components["schemas"]["StreamSet"];

/** `components.schemas.UpdatableActivity` as the document declares it. */
export type UpdatableActivity = components["schemas"]["UpdatableActivity"];

/**
 * `POST /activities`
 *
 * Create an Activity
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function createActivity(body: RequestBody): Operation<DetailedActivity> {
	return {
		method: "POST",
		path: "/activities",
		headers: { "content-type": "application/x-www-form-urlencoded" },
		body,
	};
}

type GetActivityWirePath = NonNullable<paths["/activities/{id}"]["get"]["parameters"]["path"]>;

type GetActivityWireQuery = NonNullable<paths["/activities/{id}"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getActivity}. */
export interface GetActivityQuery {
	/** To include all segments efforts. */
	readonly includeAllEfforts?: Sendable<GetActivityWireQuery["include_all_efforts"]>;
}

/**
 * `GET /activities/{id}`
 *
 * Get Activity
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getActivity(
	id: GetActivityWirePath["id"],
	query: GetActivityQuery = {},
): Operation<DetailedActivity> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}`,
		query: {
			include_all_efforts: query.includeAllEfforts,
		},
	};
}

type ReplaceActivityWirePath = NonNullable<paths["/activities/{id}"]["put"]["parameters"]["path"]>;

/**
 * `PUT /activities/{id}`
 *
 * Update Activity
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function replaceActivity(
	id: ReplaceActivityWirePath["id"],
	input: UpdatableActivity,
): Operation<DetailedActivity> {
	return {
		method: "PUT",
		path: `/activities/${encodeURIComponent(String(id))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListActivityCommentsWirePath = NonNullable<paths["/activities/{id}/comments"]["get"]["parameters"]["path"]>;

type ListActivityCommentsWireQuery = NonNullable<paths["/activities/{id}/comments"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listActivityComments}. */
export interface ListActivityCommentsQuery {
	/** Deprecated. Prefer to use after_cursor. */
	readonly page?: Sendable<ListActivityCommentsWireQuery["page"]>;

	/** Deprecated. Prefer to use page_size. */
	readonly perPage?: Sendable<ListActivityCommentsWireQuery["per_page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly pageSize?: Sendable<ListActivityCommentsWireQuery["page_size"]>;

	/** Cursor of the last item in the previous page of results, used to request the subsequent page of results.  When omitted, the first page of results is fetched. */
	readonly afterCursor?: Sendable<ListActivityCommentsWireQuery["after_cursor"]>;
}

/** What {@link listActivityComments} resolves to. */
export type ListActivityCommentsResponse =
	paths["/activities/{id}/comments"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /activities/{id}/comments`
 *
 * List Activity Comments
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listActivityComments(
	id: ListActivityCommentsWirePath["id"],
	query: ListActivityCommentsQuery = {},
): Operation<ListActivityCommentsResponse> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}/comments`,
		query: {
			page: query.page,
			per_page: query.perPage,
			page_size: query.pageSize,
			after_cursor: query.afterCursor,
		},
	};
}

type ListActivityKudosWirePath = NonNullable<paths["/activities/{id}/kudos"]["get"]["parameters"]["path"]>;

type ListActivityKudosWireQuery = NonNullable<paths["/activities/{id}/kudos"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listActivityKudos}. */
export interface ListActivityKudosQuery {
	/** Page number. Defaults to 1. */
	readonly page?: Sendable<ListActivityKudosWireQuery["page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<ListActivityKudosWireQuery["per_page"]>;
}

/** What {@link listActivityKudos} resolves to. */
export type ListActivityKudosResponse =
	paths["/activities/{id}/kudos"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /activities/{id}/kudos`
 *
 * List Activity Kudoers
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listActivityKudos(
	id: ListActivityKudosWirePath["id"],
	query: ListActivityKudosQuery = {},
): Operation<ListActivityKudosResponse> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}/kudos`,
		query: {
			page: query.page,
			per_page: query.perPage,
		},
	};
}

type ListActivityLapsWirePath = NonNullable<paths["/activities/{id}/laps"]["get"]["parameters"]["path"]>;

/** What {@link listActivityLaps} resolves to. */
export type ListActivityLapsResponse =
	paths["/activities/{id}/laps"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /activities/{id}/laps`
 *
 * List Activity Laps
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listActivityLaps(
	id: ListActivityLapsWirePath["id"],
): Operation<ListActivityLapsResponse> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}/laps`,
	};
}

type ListActivityStreamsWirePath = NonNullable<paths["/activities/{id}/streams"]["get"]["parameters"]["path"]>;

type ListActivityStreamsWireQuery = NonNullable<paths["/activities/{id}/streams"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listActivityStreams}. */
export interface ListActivityStreamsQuery {
	/** Desired stream types. */
	readonly keys: ListActivityStreamsWireQuery["keys"];

	/** Must be true. */
	readonly keyByType: Sendable<ListActivityStreamsWireQuery["key_by_type"]>;
}

/**
 * `GET /activities/{id}/streams`
 *
 * Get Activity Streams
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listActivityStreams(
	id: ListActivityStreamsWirePath["id"],
	query: ListActivityStreamsQuery,
): Operation<StreamSet> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}/streams`,
		query: {
			keys: joined(query.keys, ","),
			key_by_type: query.keyByType,
		},
	};
}

type ListActivityZonesWirePath = NonNullable<paths["/activities/{id}/zones"]["get"]["parameters"]["path"]>;

/** What {@link listActivityZones} resolves to. */
export type ListActivityZonesResponse =
	paths["/activities/{id}/zones"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /activities/{id}/zones`
 *
 * Get Activity Zones
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listActivityZones(
	id: ListActivityZonesWirePath["id"],
): Operation<ListActivityZonesResponse> {
	return {
		method: "GET",
		path: `/activities/${encodeURIComponent(String(id))}/zones`,
	};
}
