// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { components, paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.DetailedAthlete` as the document declares it. */
export type DetailedAthlete = components["schemas"]["DetailedAthlete"];

/** `components.schemas.Zones` as the document declares it. */
export type Zones = components["schemas"]["Zones"];

/**
 * `GET /athlete`
 *
 * Get Authenticated Athlete
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getAthlete(): Operation<DetailedAthlete> {
	return {
		method: "GET",
		path: "/athlete",
	};
}

/**
 * `PUT /athlete`
 *
 * Update Athlete
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function replaceAthlete(): Operation<DetailedAthlete> {
	return {
		method: "PUT",
		path: "/athlete",
	};
}

type ListAthleteActivitiesWireQuery = NonNullable<paths["/athlete/activities"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listAthleteActivities}. */
export interface ListAthleteActivitiesQuery {
	/** An epoch timestamp to use for filtering activities that have taken place before a certain time. */
	readonly before?: Sendable<ListAthleteActivitiesWireQuery["before"]>;

	/** An epoch timestamp to use for filtering activities that have taken place after a certain time. */
	readonly after?: Sendable<ListAthleteActivitiesWireQuery["after"]>;

	/** Page number. Defaults to 1. */
	readonly page?: Sendable<ListAthleteActivitiesWireQuery["page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<ListAthleteActivitiesWireQuery["per_page"]>;
}

/** What {@link listAthleteActivities} resolves to. */
export type ListAthleteActivitiesResponse =
	paths["/athlete/activities"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /athlete/activities`
 *
 * List Athlete Activities
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listAthleteActivities(
	query: ListAthleteActivitiesQuery = {},
): Operation<ListAthleteActivitiesResponse> {
	return {
		method: "GET",
		path: "/athlete/activities",
		query: {
			before: query.before,
			after: query.after,
			page: query.page,
			per_page: query.perPage,
		},
	};
}

type ListAthleteClubsWireQuery = NonNullable<paths["/athlete/clubs"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listAthleteClubs}. */
export interface ListAthleteClubsQuery {
	/** Page number. Defaults to 1. */
	readonly page?: Sendable<ListAthleteClubsWireQuery["page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<ListAthleteClubsWireQuery["per_page"]>;
}

/** What {@link listAthleteClubs} resolves to. */
export type ListAthleteClubsResponse =
	paths["/athlete/clubs"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /athlete/clubs`
 *
 * List Athlete Clubs
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listAthleteClubs(
	query: ListAthleteClubsQuery = {},
): Operation<ListAthleteClubsResponse> {
	return {
		method: "GET",
		path: "/athlete/clubs",
		query: {
			page: query.page,
			per_page: query.perPage,
		},
	};
}

/**
 * `GET /athlete/zones`
 *
 * Get Zones
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listAthleteZones(): Operation<Zones> {
	return {
		method: "GET",
		path: "/athlete/zones",
	};
}
