// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { components, paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.ActivityStats` as the document declares it. */
export type ActivityStats = components["schemas"]["ActivityStats"];

type ListAthleteRoutesWirePath = NonNullable<paths["/athletes/{id}/routes"]["get"]["parameters"]["path"]>;

type ListAthleteRoutesWireQuery = NonNullable<paths["/athletes/{id}/routes"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listAthleteRoutes}. */
export interface ListAthleteRoutesQuery {
	/** Page number. Defaults to 1. */
	readonly page?: Sendable<ListAthleteRoutesWireQuery["page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<ListAthleteRoutesWireQuery["per_page"]>;
}

/** What {@link listAthleteRoutes} resolves to. */
export type ListAthleteRoutesResponse =
	paths["/athletes/{id}/routes"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /athletes/{id}/routes`
 *
 * List Athlete Routes
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listAthleteRoutes(
	id: ListAthleteRoutesWirePath["id"],
	query: ListAthleteRoutesQuery = {},
): Operation<ListAthleteRoutesResponse> {
	return {
		method: "GET",
		path: `/athletes/${encodeURIComponent(String(id))}/routes`,
		query: {
			page: query.page,
			per_page: query.perPage,
		},
	};
}

type ListAthleteStatsWirePath = NonNullable<paths["/athletes/{id}/stats"]["get"]["parameters"]["path"]>;

/**
 * `GET /athletes/{id}/stats`
 *
 * Get Athlete Stats
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listAthleteStats(
	id: ListAthleteStatsWirePath["id"],
): Operation<ActivityStats> {
	return {
		method: "GET",
		path: `/athletes/${encodeURIComponent(String(id))}/stats`,
	};
}
