// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation } from "../operation.js";
import type { components, paths } from "../schema.js";

/** `components.schemas.DetailedClub` as the document declares it. */
export type DetailedClub = components["schemas"]["DetailedClub"];

type GetClubWirePath = NonNullable<paths["/clubs/{id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /clubs/{id}`
 *
 * Get Club
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getClub(id: GetClubWirePath["id"]): Operation<DetailedClub> {
	return {
		method: "GET",
		path: `/clubs/${encodeURIComponent(String(id))}`,
	};
}
