// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation } from "../operation.js";
import type { components, paths } from "../schema.js";

/** `components.schemas.DetailedGear` as the document declares it. */
export type DetailedGear = components["schemas"]["DetailedGear"];

type GetGearWirePath = NonNullable<paths["/gear/{id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /gear/{id}`
 *
 * Get Equipment
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getGear(id: GetGearWirePath["id"]): Operation<DetailedGear> {
	return {
		method: "GET",
		path: `/gear/${encodeURIComponent(String(id))}`,
	};
}
