// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation } from "../operation.js";
import type { components, paths } from "../schema.js";
import type { StreamSet } from "./activities.js";

/** `components.schemas.Route` as the document declares it. */
export type Route = components["schemas"]["Route"];

type GetRouteWirePath = NonNullable<paths["/routes/{id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /routes/{id}`
 *
 * Get Route
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getRoute(id: GetRouteWirePath["id"]): Operation<Route> {
	return {
		method: "GET",
		path: `/routes/${encodeURIComponent(String(id))}`,
	};
}

type GetRouteExportGpxWirePath = NonNullable<paths["/routes/{id}/export_gpx"]["get"]["parameters"]["path"]>;

/** What {@link getRouteExportGpx} resolves to. */
export type GetRouteExportGpxResponse =
	paths["/routes/{id}/export_gpx"]["get"]["responses"][200]["content"]["application/gpx+xml"];

/**
 * `GET /routes/{id}/export_gpx`
 *
 * Export Route GPX
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getRouteExportGpx(
	id: GetRouteExportGpxWirePath["id"],
): Operation<GetRouteExportGpxResponse> {
	return {
		method: "GET",
		path: `/routes/${encodeURIComponent(String(id))}/export_gpx`,
	};
}

type GetRouteExportTcxWirePath = NonNullable<paths["/routes/{id}/export_tcx"]["get"]["parameters"]["path"]>;

/** What {@link getRouteExportTcx} resolves to. */
export type GetRouteExportTcxResponse =
	paths["/routes/{id}/export_tcx"]["get"]["responses"][200]["content"]["application/tcx+xml"];

/**
 * `GET /routes/{id}/export_tcx`
 *
 * Export Route TCX
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getRouteExportTcx(
	id: GetRouteExportTcxWirePath["id"],
): Operation<GetRouteExportTcxResponse> {
	return {
		method: "GET",
		path: `/routes/${encodeURIComponent(String(id))}/export_tcx`,
	};
}

type ListRouteStreamsWirePath = NonNullable<paths["/routes/{id}/streams"]["get"]["parameters"]["path"]>;

/**
 * `GET /routes/{id}/streams`
 *
 * Get Route Streams
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listRouteStreams(
	id: ListRouteStreamsWirePath["id"],
): Operation<StreamSet> {
	return {
		method: "GET",
		path: `/routes/${encodeURIComponent(String(id))}/streams`,
	};
}
