// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import { joined } from "../query.js";
import type { Operation, QueryValue } from "../operation.js";
import type { components, paths } from "../schema.js";
import type { StreamSet } from "./activities.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.DetailedSegmentEffort` as the document declares it. */
export type DetailedSegmentEffort = components["schemas"]["DetailedSegmentEffort"];

type ListSegmentEffortsWireQuery = NonNullable<paths["/segment_efforts"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listSegmentEfforts}. */
export interface ListSegmentEffortsQuery {
	/** The identifier of the segment. */
	readonly segmentId: Sendable<ListSegmentEffortsWireQuery["segment_id"]>;

	/** ISO 8601 formatted date time. */
	readonly startDateLocal?: Sendable<ListSegmentEffortsWireQuery["start_date_local"]>;

	/** ISO 8601 formatted date time. */
	readonly endDateLocal?: Sendable<ListSegmentEffortsWireQuery["end_date_local"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<ListSegmentEffortsWireQuery["per_page"]>;
}

/** What {@link listSegmentEfforts} resolves to. */
export type ListSegmentEffortsResponse =
	paths["/segment_efforts"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /segment_efforts`
 *
 * List Segment Efforts
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listSegmentEfforts(
	query: ListSegmentEffortsQuery,
): Operation<ListSegmentEffortsResponse> {
	return {
		method: "GET",
		path: "/segment_efforts",
		query: {
			segment_id: query.segmentId,
			start_date_local: query.startDateLocal,
			end_date_local: query.endDateLocal,
			per_page: query.perPage,
		},
	};
}

type GetSegmentEffortWirePath = NonNullable<paths["/segment_efforts/{id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /segment_efforts/{id}`
 *
 * Get Segment Effort
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getSegmentEffort(
	id: GetSegmentEffortWirePath["id"],
): Operation<DetailedSegmentEffort> {
	return {
		method: "GET",
		path: `/segment_efforts/${encodeURIComponent(String(id))}`,
	};
}

type ListSegmentEffortStreamsWirePath = NonNullable<paths["/segment_efforts/{id}/streams"]["get"]["parameters"]["path"]>;

type ListSegmentEffortStreamsWireQuery = NonNullable<paths["/segment_efforts/{id}/streams"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listSegmentEffortStreams}. */
export interface ListSegmentEffortStreamsQuery {
	/** The types of streams to return. */
	readonly keys: ListSegmentEffortStreamsWireQuery["keys"];

	/** Must be true. */
	readonly keyByType: Sendable<ListSegmentEffortStreamsWireQuery["key_by_type"]>;
}

/**
 * `GET /segment_efforts/{id}/streams`
 *
 * Get Segment Effort Streams
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listSegmentEffortStreams(
	id: ListSegmentEffortStreamsWirePath["id"],
	query: ListSegmentEffortStreamsQuery,
): Operation<StreamSet> {
	return {
		method: "GET",
		path: `/segment_efforts/${encodeURIComponent(String(id))}/streams`,
		query: {
			keys: joined(query.keys, ","),
			key_by_type: query.keyByType,
		},
	};
}
