// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import { joined } from "../query.js";
import type { Operation, QueryValue, RequestBody } from "../operation.js";
import type { components, paths } from "../schema.js";
import type { StreamSet } from "./activities.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.DetailedSegment` as the document declares it. */
export type DetailedSegment = components["schemas"]["DetailedSegment"];

/** `components.schemas.ExplorerResponse` as the document declares it. */
export type ExplorerResponse = components["schemas"]["ExplorerResponse"];

type GetSegmentExploreWireQuery = NonNullable<paths["/segments/explore"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getSegmentExplore}. */
export interface GetSegmentExploreQuery {
	/** The latitude and longitude for two points describing a rectangular boundary for the search: [southwest corner latitutde, southwest corner longitude, northeast corner latitude, northeast corner longitude] */
	readonly bounds: GetSegmentExploreWireQuery["bounds"];

	/** Desired activity type. */
	readonly activityType?: Sendable<GetSegmentExploreWireQuery["activity_type"]>;

	/** The minimum climbing category. */
	readonly minCat?: Sendable<GetSegmentExploreWireQuery["min_cat"]>;

	/** The maximum climbing category. */
	readonly maxCat?: Sendable<GetSegmentExploreWireQuery["max_cat"]>;
}

/**
 * `GET /segments/explore`
 *
 * Explore segments
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getSegmentExplore(
	query: GetSegmentExploreQuery,
): Operation<ExplorerResponse> {
	return {
		method: "GET",
		path: "/segments/explore",
		query: {
			bounds: joined(query.bounds, ","),
			activity_type: query.activityType,
			min_cat: query.minCat,
			max_cat: query.maxCat,
		},
	};
}

type GetSegmentStarredWireQuery = NonNullable<paths["/segments/starred"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getSegmentStarred}. */
export interface GetSegmentStarredQuery {
	/** Page number. Defaults to 1. */
	readonly page?: Sendable<GetSegmentStarredWireQuery["page"]>;

	/** Number of items per page. Defaults to 30. */
	readonly perPage?: Sendable<GetSegmentStarredWireQuery["per_page"]>;
}

/** What {@link getSegmentStarred} resolves to. */
export type GetSegmentStarredResponse =
	paths["/segments/starred"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /segments/starred`
 *
 * List Starred Segments
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getSegmentStarred(
	query: GetSegmentStarredQuery = {},
): Operation<GetSegmentStarredResponse> {
	return {
		method: "GET",
		path: "/segments/starred",
		query: {
			page: query.page,
			per_page: query.perPage,
		},
	};
}

type GetSegmentWirePath = NonNullable<paths["/segments/{id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /segments/{id}`
 *
 * Get Segment
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getSegment(id: GetSegmentWirePath["id"]): Operation<DetailedSegment> {
	return {
		method: "GET",
		path: `/segments/${encodeURIComponent(String(id))}`,
	};
}

type ReplaceSegmentStarredWirePath = NonNullable<paths["/segments/{id}/starred"]["put"]["parameters"]["path"]>;

/**
 * `PUT /segments/{id}/starred`
 *
 * Star Segment
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function replaceSegmentStarred(
	id: ReplaceSegmentStarredWirePath["id"],
	body: RequestBody,
): Operation<DetailedSegment> {
	return {
		method: "PUT",
		path: `/segments/${encodeURIComponent(String(id))}/starred`,
		headers: { "content-type": "application/x-www-form-urlencoded" },
		body,
	};
}

type ListSegmentStreamsWirePath = NonNullable<paths["/segments/{id}/streams"]["get"]["parameters"]["path"]>;

type ListSegmentStreamsWireQuery = NonNullable<paths["/segments/{id}/streams"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listSegmentStreams}. */
export interface ListSegmentStreamsQuery {
	/** The types of streams to return. */
	readonly keys: ListSegmentStreamsWireQuery["keys"];

	/** Must be true. */
	readonly keyByType: Sendable<ListSegmentStreamsWireQuery["key_by_type"]>;
}

/**
 * `GET /segments/{id}/streams`
 *
 * Get Segment Streams
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function listSegmentStreams(
	id: ListSegmentStreamsWirePath["id"],
	query: ListSegmentStreamsQuery,
): Operation<StreamSet> {
	return {
		method: "GET",
		path: `/segments/${encodeURIComponent(String(id))}/streams`,
		query: {
			keys: joined(query.keys, ","),
			key_by_type: query.keyByType,
		},
	};
}
