// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/strava-dung-beetle/refs/heads/master/strava3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, RequestBody } from "../operation.js";
import type { components, paths } from "../schema.js";

/** `components.schemas.Upload` as the document declares it. */
export type Upload = components["schemas"]["Upload"];

/**
 * `POST /uploads`
 *
 * Upload Activity
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function createUpload(body: RequestBody): Operation<Upload> {
	return {
		method: "POST",
		path: "/uploads",
		headers: { "content-type": "multipart/form-data" },
		body,
	};
}

type GetUploadWirePath = NonNullable<paths["/uploads/{uploadId}"]["get"]["parameters"]["path"]>;

/**
 * `GET /uploads/{uploadId}`
 *
 * Get Upload
 *
 * @security strava_oauth: OAuth2, token from https://www.strava.com/api/v3/oauth/token, sent as `authorization: Bearer <token>`, scopes `public`
 */
export function getUpload(uploadId: GetUploadWirePath["uploadId"]): Operation<Upload> {
	return {
		method: "GET",
		path: `/uploads/${encodeURIComponent(String(uploadId))}`,
	};
}
